const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {CloudSpeech,PcmEncoder}=require('../src/cloud-speech.cjs');
const {cloudRequest}=require('../src/cloud-llm.cjs');
const {CloudKeys}=require('../src/cloud-keys.cjs');
const {planCommand}=require('../src/command-plan.cjs');
class Socket extends EventEmitter{constructor(url,options){super();this.url=url;this.options=options;this.sent=[];this.bufferedAmount=0;}send(data){this.sent.push(JSON.parse(data));}terminate(){this.terminated=true;}receive(e){this.emit('message',Buffer.from(JSON.stringify(e)));}}
async function ready(provider,options={}){const s=new CloudSpeech(provider,'test-secret-not-real',{WebSocketClass:Socket,...options});s.socket.emit('open');s.socket.receive(provider==='openai'?{type:'session.updated'}:{setupComplete:{}});await s.ready;return s;}
const pcm=n=>Buffer.from(new Float32Array(n).fill(.1).buffer);
test('PCM resampling is independent of chunk boundaries at both rates',()=>{for(const rate of [16000,24000]){const input=Buffer.from(Float32Array.from({length:16001},(_,i)=>Math.sin(i/50)).buffer),a=new PcmEncoder(rate),b=new PcmEncoder(rate);const all=Buffer.from(a.encode(input,true),'base64');const parts=[];for(let i=0;i<input.length;i+=512)parts.push(Buffer.from(b.encode(input.subarray(i,i+512)),'base64'));parts.push(Buffer.from(b.encode(Buffer.alloc(0),true),'base64'));assert.deepEqual(Buffer.concat(parts),all);assert.ok(Math.abs(all.length/2-16001*rate/16000)<=1);}});
test('OpenAI sends partials before stop and waits for out-of-order final transcripts',async()=>{const updates=[],s=await ready('openai',{changed:e=>updates.push(e.text)});try{assert.equal(s.socket.sent[0].session.audio.input.transcription.model,'gpt-live-transcribe');await s.request('audio',pcm(240000));s.socket.receive({type:'input_audio_buffer.committed',item_id:'a',previous_item_id:null});s.socket.receive({type:'conversation.item.input_audio_transcription.delta',item_id:'a',delta:'途中'});assert.equal(updates.at(-1),'途中');await s.request('audio',pcm(3200));const finish=s.request('stop');await Promise.resolve();s.socket.receive({type:'input_audio_buffer.committed',item_id:'b',previous_item_id:'a'});s.socket.receive({type:'conversation.item.input_audio_transcription.completed',item_id:'b',transcript:'後半。'});let ended=false;finish.then(()=>ended=true);await Promise.resolve();assert.equal(ended,false);s.socket.receive({type:'conversation.item.input_audio_transcription.completed',item_id:'a',transcript:'前半。'});assert.equal((await finish).text,'前半。後半。');}finally{await s.close();}});
test('Gemini replaces interim hypotheses, preserves finals, and flushes before stop returns',async()=>{const s=await ready('gemini');try{await s.request('audio',pcm(3200));assert.equal(s.socket.sent[0].setup.model,'models/gemini-3.5-transcribe-live');s.socket.receive({serverContent:{interimInputTranscription:{text:'歯'}}});s.socket.receive({serverContent:{interimInputTranscription:{text:'橋'}}});assert.equal(s.text,'橋');s.socket.receive({serverContent:{inputTranscription:{text:'橋を渡る。'},turnComplete:true}});const finish=s.request('stop');await Promise.resolve();s.socket.receive({serverContent:{inputTranscription:{text:'到着。'},turnComplete:true}});assert.equal((await finish).text,'橋を渡る。到着。');assert.deepEqual(s.socket.sent.at(-1).realtimeInput.activityEnd,{});}finally{await s.close();}});
test('Network errors preserve partial text and never leak provider error payload or credentials',async()=>{const s=await ready('openai');s.socket.receive({type:'conversation.item.input_audio_transcription.delta',item_id:'a',delta:'保存する原文'});s.socket.receive({error:{message:'test-secret-not-real'}});await assert.rejects(s.request('audio',pcm(100)),e=>!e.message.includes('test-secret'));assert.equal(s.text,'保存する原文');assert.equal(s.socket.terminated,true);await s.close();});
test('Finish timeout is an explicit failure and empty recordings need no commit',async()=>{const empty=await ready('openai');assert.deepEqual(await empty.request('stop'),{text:''});await empty.close();const s=await ready('gemini',{timeout:15});await s.request('audio',pcm(2000));await assert.rejects(s.request('stop'),/最終結果/);await s.close();});
test('WebSocket backpressure stops sending instead of accumulating audio',async()=>{const s=await ready('gemini');s.socket.bufferedAmount=1024*1024+1;await assert.rejects(s.request('audio',pcm(2000)),/追いつかない/);await s.close();});
test('Cloud LLM uses exact model, structured responses, headers, and no response storage',async()=>{for(const provider of ['openai','gemini']){let seen;const request=cloudRequest(provider,'test-secret',null,async(url,init)=>{seen={url,init,body:JSON.parse(init.body)};return{ok:true,json:async()=>provider==='openai'?{status:'completed',output:[{content:[{type:'output_text',text:'{"selected":[],"edits":[]}'}]}]}:{candidates:[{finishReason:'STOP',content:{parts:[{text:'{"selected":[],"edits":[]}'}]}}]}};});assert.deepEqual(await request({messages:[{role:'system',content:'辞書は参考 /no_think'},{role:'user',content:'原文'}],schema:{type:'object',properties:{},additionalProperties:false}}),{selected:[],edits:[]});assert.equal(seen.url.includes('test-secret'),false);if(provider==='openai'){assert.equal(seen.body.model,'gpt-5.6-luna');assert.equal(seen.body.store,false);}else assert.ok(seen.url.includes('gemini-3.5-flash'));}});
test('HTTP errors are explicit, redact body, do not retry or fallback',async()=>{let calls=0;const request=cloudRequest('openai','key',null,async()=>{calls++;return{ok:false,status:429,text:async()=>'secret'};});await assert.rejects(request({messages:[],schema:{}}),/HTTP 429/);assert.equal(calls,1);});
test('Command API plans go through the existing key allowlist',async()=>{await assert.rejects(planCommand('右へ',{cloudRequest:async()=>({actions:[{key:'Shell',text:'x',count:1}],reason:''})}),/不正/);assert.deepEqual((await planCommand('右へ',{cloudRequest:async()=>({actions:[{key:'Right',text:'',count:1}],reason:''})})).actions,[{key:'Right',text:'',count:1}]);});
test('Keys are opaque on disk, never returned by status, and encryption failure refuses saving',async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'gourdy-key-test-'));try{const crypt={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s.split('').reverse().join('')),decryptString:b=>b.toString().split('').reverse().join('')},keys=new CloudKeys(folder,crypt);await keys.load();await keys.save('openai','test-secret-key');assert.equal(await keys.read('openai'),'test-secret-key');assert.equal((await fs.readFile(path.join(folder,'openai.key'),'utf8')).includes('test-secret-key'),false);assert.deepEqual(keys.present,{openai:true,gemini:false});await keys.remove('openai');assert.equal(keys.present.openai,false);crypt.isEncryptionAvailable=()=>false;await assert.rejects(keys.save('gemini','test-secret-key'),/暗号化/);assert.throws(()=>keys.file('../bad'),/不正/);}finally{await fs.rm(folder,{recursive:true,force:true});}});

test('Gemini transcription final completes manual stop without conversation turnComplete',async()=>{const s=await ready('gemini');try{await s.request('audio',pcm(3200));s.socket.receive({serverContent:{interimInputTranscription:{text:'途中'}}});const finish=s.request('stop');await Promise.resolve();s.socket.receive({serverContent:{inputTranscription:{text:'確定した文章。'}}});assert.equal((await finish).text,'確定した文章。');}finally{await s.close();}});
test('Invalid OpenAI key gives an actionable error without echoing API payload',async()=>{const s=await ready('openai');s.socket.receive({error:{code:'invalid_api_key',message:'test-secret-not-real'}});await assert.rejects(s.request('audio',pcm(10)),e=>e.message.includes('登録し直して')&&!e.message.includes('test-secret'));await s.close();});
