const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{randomUUID}=require('node:crypto');
const {Meetings,transcript}=require('../src/meetings.cjs');
async function fixture(options={},n=4){const folder=await fs.mkdtemp(path.join(os.tmpdir(),'okosy-meeting-')),source=path.join(folder,'source.wav');await fs.writeFile(source,'test');const s=await fs.stat(source),job={id:randomUUID(),version:1,source,name:'test.wav',stamp:{size:s.size,mtimeMs:s.mtimeMs},duration:n*60,audioStream:0,at:new Date().toISOString(),state:'ready',parts:Array.from({length:n},(_,i)=>({start:i*60,end:(i+1)*60,state:'pending',attempts:0}))};const manager=new Meetings(folder,'',()=>({}),{decodePart:async(j,p)=>Buffer.from(String(p.start)),recognizePart:async pcm=>'原文'+pcm.toString(),refinePart:async t=>t+'。',retryDelay:0,...options});await manager.save(job);return {manager,job};}
test('失敗区間を3回で止めて後続を保存。再起動後に失敗区間だけ再開',async()=>{const calls=[];const {manager,job}=await fixture({recognizePart:async b=>{const n=Number(b.toString());calls.push(n);if(n===60)throw new Error('認識プロセス故障');return '結果'+n}});const partial=await manager.run(job.id);assert.equal(partial.state,'partial');assert.deepEqual(calls,[0,60,60,60,120,180]);assert.equal(partial.parts[1].error,'認識プロセス故障');const next=new Meetings(manager.folder,'',()=>({}),{decodePart:manager.decodePart,recognizePart:async b=>{assert.equal(b.toString(),'60');return '復旧'},refinePart:async t=>t,retryDelay:0});const completed=await next.run(job.id);assert.equal(completed.state,'done');assert.equal(completed.parts[0].attempts,1);});
test('補正失敗でも原文を先に保存し、補正再試行でASRを再実行しない',async()=>{let asr=0,correction=0;const {manager,job}=await fixture({recognizePart:async()=>{asr++;return '原文'},refinePart:async()=>{correction++;assert.equal((await manager.read(job.id)).parts[0].raw,'原文');if(correction<3)throw new Error('LLM故障');return '原文。'}},1);await manager.run(job.id);assert.equal(asr,1);assert.equal(correction,3)});
test('中断後の再開と長文全文出力。保存した区間はやり直さない',async()=>{const controller=new AbortController();const {manager,job}=await fixture({recognizePart:async()=> '長'.repeat(7000)},3);await assert.rejects(manager.run(job.id,controller.signal,j=>{if(j.parts[0].state==='done')controller.abort()}));assert.equal((await manager.read(job.id)).state,'paused');const done=await manager.run(job.id);assert.equal(done.parts[0].attempts,1);assert.ok(transcript(done).length>21000);});
test('元ファイル変更を検出して再開を拒否',async()=>{const {manager,job}=await fixture();await fs.appendFile(job.source,'changed');await assert.rejects(manager.run(job.id),/変更/);assert.equal((await manager.read(job.id)).parts[0].attempts,0)});
test('3区間連続失敗で早期停止し、残りを未着手で残す',async()=>{const {manager,job}=await fixture({recognizePart:async()=>{throw new Error('全体障害')}},10);const result=await manager.run(job.id);assert.equal(result.state,'partial');assert.match(result.error,/3区間連続/);assert.equal(result.parts[3].attempts,0)});
test('保存失敗は処理を継続せず明示する',async()=>{const {manager,job}=await fixture();manager.save=async()=>{throw new Error('disk full')};await assert.rejects(manager.run(job.id),/disk full/);assert.equal(manager.running,false)});

test('無音境界と重なりを保存し中断・再開でも確定区間を変更しない',async()=>{
 const decoded=[];const {manager,job}=await fixture({decodePart:async(j,p)=>{decoded.push({...p});const samples=Math.round((p.end-p.start)*16000),b=Buffer.alloc(samples*4);for(let i=0;i<samples;i++){const t=p.start+i/16000;b.writeFloatLE(t>=61&&t<62?0:.08,i*4);}return b;},recognizePart:async()=> '境界をまたぐ単語です'},2);
 job.boundaryPolicy='silence-v1';await manager.save(job);const signal=new AbortController();
 await assert.rejects(manager.run(job.id,signal.signal,j=>{if(j.parts[0].state==='done')signal.abort()}));
 const saved=await manager.read(job.id);assert.equal(saved.parts[0].boundary.reason,'silence');assert.equal(saved.parts[0].end,saved.parts[1].start);assert.ok(Math.abs(saved.parts[0].audioEnd-saved.parts[1].audioStart-.2)<1e-8);
 const first=structuredClone(saved.parts[0]);const resumed=await manager.run(job.id);assert.equal(resumed.state,'done');assert.deepEqual(resumed.parts[0],first);assert.equal(decoded.length,3);
});
