const test=require('node:test'),assert=require('node:assert/strict');const {shortcutKeys,shortcutLabel}=require('../src/shortcuts.js');const {defaults,validate}=require('../src/store.cjs');
test('recording supports side-specific modifiers and punctuation',()=>{assert.equal(defaults.shortcut,'ControlRight');for(const [key,vk] of [['ControlRight',163],['ControlLeft',162],['AltRight',165],['AltLeft',164]]){assert.deepEqual(shortcutKeys(key),[vk]);assert.equal(validate({...defaults,shortcut:key}).shortcut,key);}assert.deepEqual(shortcutKeys('Alt+,'),[18,188]);assert.equal(shortcutLabel('ControlRight'),'Ctrl（右）');assert.equal(shortcutLabel('Alt+,'),'Alt + ,');});
test('invalid shortcuts are rejected and side-specific hold commands are accepted',()=>{for(const key of ['A','Control','ControlRight+A','Alt+','Alt+Alt+A','Shift+A'])assert.throws(()=>shortcutKeys(key));assert.equal(defaults.commandShortcut,'AltRight');assert.equal(validate({...defaults,commandShortcut:'AltRight'}).commandShortcut,'AltRight');assert.throws(()=>validate({...defaults,commandEnabled:true,shortcut:'AltRight'}));});
test('native modifier tap distinguishes sides, combinations, repeat and mouse cancellation',{skip:process.platform!=='win32'},()=>{
 const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');fs.mkdirSync('artifacts',{recursive:true});const out=fs.mkdtempSync(path.resolve('artifacts/modifier-test-')),source=path.join(out,'Test.cs'),exe=path.join(out,'Test.exe');
 fs.writeFileSync(source,`using System;class TapTest{static void Check(bool x){if(!x)throw new Exception("tap assertion");}static void Main(){foreach(int k in new[]{162,163,164,165}){var t=new ModifierTap(k);Check(!t.Key(k,true,false));Check(!t.Key(k,true,false));Check(t.Key(k,false,false));Check(!t.Key(k,false,false));t.Key(k,true,false);t.Key(67,true,false);t.Key(67,false,false);Check(!t.Key(k,false,false));t.Key(k,true,true);Check(!t.Key(k,false,false));t.Key(k,true,false);t.Cancel();Check(!t.Key(k,false,false));int other=k==163?162:163;Check(!t.Key(other,true,false));Check(!t.Key(other,false,false));}var hold=new ModifierHold(165);Check(!hold.Key(164,true,false));Check(hold.Key(165,true,false));Check(!hold.Key(165,true,false));Check(!hold.Key(165,false,false));Check(!hold.Key(165,true,true));Check(!hold.Key(165,false,false));Check(hold.Key(165,true,false));Console.WriteLine("PASS");}}`);
 execFileSync(path.join(process.env.WINDIR,'Microsoft.NET/Framework64/v4.0.30319/csc.exe'),['/nologo','/target:exe','/main:TapTest','/reference:System.Windows.Forms.dll','/out:'+exe,path.resolve('src/ModifierShortcut.cs'),source]);assert.match(execFileSync(exe,{encoding:'utf8'}),/PASS/);
});
test('modifier chord ignores unmapped virtual state but keeps physical keys and mouse',{skip:process.platform!=='win32'},()=>{
 const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
 const out=fs.mkdtempSync(path.resolve('artifacts/modifier-state-')),source=path.join(out,'Test.cs'),exe=path.join(out,'Test.exe');
 fs.writeFileSync(source,`using System;class StateTest{static void Check(bool x){if(!x)throw new Exception("chord classification");}static void Main(){Check(!ModifierTap.IsChordKey(0xF0,0));Check(!ModifierTap.IsChordKey(0xE5,0));Check(!ModifierTap.IsChordKey(0xE7,0));Check(!ModifierTap.IsChordKey(17,29));foreach(int k in new[]{1,2,4,5,6})Check(ModifierTap.IsChordKey(k,0));foreach(int k in new[]{65,91,92,162,163,164,165,0xE2})Check(ModifierTap.IsChordKey(k,29));var tap=new ModifierTap(163);bool phantomHeld=ModifierTap.IsChordKey(0xF0,0);tap.Key(163,true,phantomHeld);Check(tap.Key(163,false,false));tap.Key(163,true,ModifierTap.IsChordKey(65,30));Check(!tap.Key(163,false,false));Console.WriteLine("PASS");}}`);
 execFileSync(path.join(process.env.WINDIR,'Microsoft.NET/Framework64/v4.0.30319/csc.exe'),['/nologo','/target:exe','/main:StateTest','/reference:System.Windows.Forms.dll','/out:'+exe,path.resolve('src/ModifierShortcut.cs'),source]);
 assert.match(execFileSync(exe,{encoding:'utf8'}),/PASS/);
});
