const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){const events={},counts={start:0,end:0,force:0},elements=new Map();let rejectFinish;const element=()=>({style:{setProperty(){}},classList:{toggle(){}},setAttribute(){},getAttribute(){return ""},children:[],append(e){this.children.push(e)}});const api={on:(name,fn)=>events[name]=fn,miniSettings:async()=>({shortcut:'Super+J',accent:'#262626'}),reportError:async()=>{},liveStart:async()=>{counts.start++},liveEnd:async()=>{counts.end++},liveFinish:()=>new Promise((_,reject)=>rejectFinish=reject),forceStop:async()=>{counts.force++;rejectFinish?.(new Error('cancelled'));},cancel:async()=>{}};
const ctx=vm.createContext({window:{dictation:api},document:{getElementById:id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id)},createElement:element,documentElement:element(),body:element()},navigator:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){}}],getAudioTracks:()=>[{addEventListener(){}}]})}},LiveRecorder:class{constructor(){this.context={state:'running',close:async()=>{this.context.state='closed'}}}async start(){}async stop(){}},Microphone:{...require('../src/microphone.js'),verify(){}},setInterval:()=>1,clearInterval(){},setTimeout,Uint8Array,console});vm.runInContext(fs.readFileSync('src/renderer.js','utf8'),ctx);return {ctx,counts,events,api};}
test('blocked recording restarts with one shortcut',async()=>{const {ctx,counts}=setup();await new Promise(setImmediate);await vm.runInContext('toggle()',ctx);vm.runInContext("error(new Error('verification failed'))",ctx);await vm.runInContext('toggle()',ctx);assert.equal(counts.force,1);assert.equal(counts.start,2);assert.equal(vm.runInContext('phase',ctx),'recording');});
test('processing shortcut cancels pending finish then starts a fresh recording',async()=>{const {ctx,counts}=setup();await new Promise(setImmediate);await vm.runInContext('toggle()',ctx);const stopping=vm.runInContext('toggle()',ctx);await new Promise(setImmediate);assert.equal(vm.runInContext('phase',ctx),'processing');await vm.runInContext('toggle()',ctx);await stopping;assert.equal(counts.force,1);assert.equal(counts.start,2);assert.equal(vm.runInContext('phase',ctx),'recording');});


test('starting shortcut aborts a pending start and restarts without overlapping sessions',async()=>{const {ctx,counts,api}=setup();await new Promise(setImmediate);let rejectStart;api.liveStart=()=>{counts.start++;return counts.start===1?new Promise((_,reject)=>rejectStart=reject):Promise.resolve();};api.forceStop=async()=>{counts.force++;rejectStart(new Error('cancelled'));};const first=vm.runInContext('toggle()',ctx);await new Promise(setImmediate);assert.equal(vm.runInContext('phase',ctx),'starting');await vm.runInContext('toggle()',ctx);await first;assert.equal(counts.start,2);assert.equal(vm.runInContext('phase',ctx),'recording');});

test('unresponsive microphone can be cancelled; late old stream is released',async()=>{const {ctx,counts}=setup();await new Promise(setImmediate);let resolveOld,requests=0,released=0;ctx.navigator.mediaDevices.getUserMedia=()=>++requests===1?new Promise(resolve=>resolveOld=resolve):Promise.resolve({getTracks:()=>[{stop(){}}],getAudioTracks:()=>[{addEventListener(){}}]});const first=vm.runInContext('toggle()',ctx);await new Promise(setImmediate);await vm.runInContext('toggle()',ctx);await first;assert.equal(counts.start,2);assert.equal(vm.runInContext('phase',ctx),'recording');resolveOld({getTracks:()=>[{stop(){released++}}]});await new Promise(setImmediate);assert.equal(released,1);assert.equal(vm.runInContext('phase',ctx),'recording');});
test('backend startup failure releases a pending microphone request',async()=>{const {ctx,api}=setup();await new Promise(setImmediate);let resolveOld,released=0;ctx.navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>resolveOld=resolve);api.liveStart=async()=>{throw new Error('input unavailable')};await vm.runInContext('toggle()',ctx);assert.equal(vm.runInContext('phase',ctx),'idle');resolveOld({getTracks:()=>[{stop(){released++}}]});await new Promise(setImmediate);assert.equal(released,1);});
