// Meeting files have their own durable results and are not clipped by dictation history limits.
let meeting=null,meetingRunning=false,previewLoading=false;
const meetingTime=s=>[Math.floor(s/3600),Math.floor(s/60)%60,Math.floor(s)%60].map(n=>String(n).padStart(2,'0')).join(':');
const meetingState={ready:'開始前',running:'処理中',paused:'中断',partial:'一部未完了',error:'要確認',done:'完了'};
function meetingControls(){const running=data?.phase!=='idle';$('choose-media').disabled=running;$('run-meeting').disabled=running||!meeting||meeting.state==='done';$('cancel-media').hidden=!running||meeting?.state!=='running';$('cancel-media').disabled=false;for(const id of ['copy-meeting','export-meeting'])$(id).disabled=!meeting;$('delete-meeting').disabled=running||!meeting;}
async function meetingList(){const previous=meeting?.id||$('meeting-list').value,entries=await api.meetingList();$('meeting-list').replaceChildren(new Option('会議を選択',''));for(const entry of entries)$('meeting-list').add(new Option(`${entry.name} · ${entry.done}/${entry.total} · ${meetingState[entry.state]||entry.state}`,entry.id));$('meeting-list').value=previous;}
function showMeeting(job){if(meeting?.id!==job.id){$('subtitle-text').textContent='';$('copy-subtitles').hidden=true;}meeting=job;$('subtitle-options').hidden=!job.subtitleTracks?.length;const selected=$('subtitle-track').value;$('subtitle-track').replaceChildren();for(const track of job.subtitleTracks||[])$('subtitle-track').add(new Option([track.language,track.title,track.codec,track.supported?'':'画像字幕・非対応'].filter(Boolean).join(' · '),String(track.index)));if([...$('subtitle-track').options].some(o=>o.value===selected))$('subtitle-track').value=selected;$('meeting-detail').hidden=false;$('meeting-name').textContent=`${job.name} · ${meetingTime(job.duration)}`;const done=job.parts.filter(p=>p.state==='done').length,errors=job.parts.filter(p=>p.state==='error').length;$('meeting-progress').textContent=`${meetingState[job.state]||job.state} · ${done}/${job.parts.length}区間を保存済み`+(errors?` · ${errors}区間で失敗`:'')+(job.error?` · ${job.error}`:'');$('meeting-progress-bar').max=job.parts.length;$('meeting-progress-bar').value=done;$('run-meeting').textContent=job.state==='done'?'文字起こし完了':job.parts.some(p=>p.raw!==undefined)||job.state!=='ready'?'未完了の区間を再開':'文字起こしを開始';const expanded=new Set([...$('meeting-parts').children].filter(d=>d.open).map(d=>d.dataset.index));$('meeting-parts').replaceChildren();job.parts.forEach((part,i)=>{const row=document.createElement('details');row.dataset.index=i;row.open=expanded.has(String(i))||part.state==='error';const summary=document.createElement('summary');summary.textContent=`${meetingTime(part.start)}–${meetingTime(part.end)} · `+(job.state!=='running'&&['recognizing','correcting'].includes(part.state)?(part.raw!==undefined?'原文保存済み・補正待ち':'未完了'):({pending:'待機',recognizing:'認識中',correcting:'補正中（原文保存済み）',done:part.raw?'保存済み':'認識文字なし（再生で確認）',error:'失敗'}[part.state]||part.state))+(part.attempts>1?` · 試行${part.attempts}回`:'');const content=document.createElement('p');content.textContent=part.corrected??part.raw??'まだ認識していません。';row.append(summary,content);const play=document.createElement('button');play.className='paste-button';play.textContent='この区間を再生';play.onclick=async()=>{const loaded=await loadPreview(part.start);try{if(loaded)await $('media-preview').play();}catch(e){report(e)}};row.append(play);if(part.raw!==undefined){const raw=document.createElement('details'),label=document.createElement('summary'),text=document.createElement('p');label.textContent=part.corrected===part.raw?'認識原文（補正なし）':'認識原文と比較';text.textContent=part.raw;raw.append(label,text);row.append(raw);}if(part.error){const error=document.createElement('p');error.className='error';error.textContent=part.error;row.append(error)}$('meeting-parts').append(row)});meetingControls();}
async function loadPreview(start=0){if(!meeting||previewLoading)return;previewLoading=true;meetingControls();$('preview-note').textContent='プレビューを準備中…';try{const id=meeting.id,result=await api.meetingPreview(id,start);if(meeting?.id!==id)return;$('media-preview').src=result.url;$('media-preview').load();$('preview-note').textContent=`${meetingTime(result.start)}–${meetingTime(result.end)}の音声。再生ボタンで確認できます。`;return true;}catch(error){$('preview-note').textContent=error.message;report(error)}finally{previewLoading=false;meetingControls()}}

$('media-preview').onerror=()=>{$('preview-note').textContent='プレビューを再生できません。区間の「この区間を再生」を押し直してください。';};
$('choose-media').onclick=async()=>{try{if(!await saveCurrent(true))return;$('choose-media').disabled=true;const job=await api.meetingSelect();if(!job)return;$('media-preview').pause();showMeeting(job);await meetingList();await loadPreview();}catch(error){report(error)}finally{meetingControls()}};
$('meeting-list').onchange=async()=>{try{const id=$('meeting-list').value;$('media-preview').pause();$('media-preview').removeAttribute('src');$('media-preview').load();if(!id){meeting=null;$('meeting-detail').hidden=true;return}const job=await api.meetingRead(id);if(job.state==='running'&&data.phase==='idle')job.state='paused';showMeeting(job);await loadPreview();}catch(error){report(error)}};
$('run-meeting').onclick=async()=>{if(!meeting||meetingRunning)return;meetingRunning=true;$('media-preview').pause();try{showMeeting(await api.meetingRun(meeting.id));}catch(error){report(error)}finally{meetingRunning=false;await meetingList();meetingControls()}};
$('cancel-media').onclick=()=>api.cancelMedia().catch(report);
$('copy-meeting').onclick=async()=>{try{await api.meetingCopy(meeting.id);$('status').classList.remove('error');$('status').textContent='コピーしました。';}catch(error){report(error)}};
$('export-meeting').onclick=async()=>{try{if(await api.meetingExport(meeting.id)){$('status').classList.remove('error');$('status').textContent='会議の全文を書き出しました。';}}catch(error){report(error)}};
$('delete-meeting').onclick=()=>{pendingAction={meetingId:meeting.id};$('confirm-title').textContent='この会議の結果を削除してよろしいですか？';$('confirm-description').textContent='途中結果と再開情報も削除します。元の音声・動画は残ります。';$('confirm-dialog').showModal();$('confirm-cancel').focus();};
api.on('meeting-changed',({job,index,attempt})=>{if(!meeting||meeting.id===job.id){showMeeting(job);if(index!==undefined)$('meeting-progress').textContent+=` · ${index+1}区間目（今回${attempt}/3回）`}});
api.on('phase-changed',()=>meetingControls());
meetingList().catch(report);

$('read-subtitles').onclick=async()=>{try{$('subtitle-text').textContent=await api.meetingSubtitles(meeting.id,Number($('subtitle-track').value));$('copy-subtitles').hidden=!$('subtitle-text').textContent;}catch(e){report(e)}};
$('copy-subtitles').onclick=async()=>{try{await api.copySubtitles($('subtitle-text').textContent);$('status').textContent='字幕をコピーしました。';}catch(e){report(e)}};
