const api=window.dictation,$=id=>document.getElementById(id),tabs=[...document.querySelectorAll('nav [role=tab]')],indicator=document.querySelector('.indicator');
let data,chain=Promise.resolve(),pendingAction=null,ready=false,historySignature=null;
function report(e){$('status').textContent=e.message||String(e);$('status').classList.add('error');}
function success(){ $('status').textContent='保存済み';$('status').classList.remove('error'); }
function persist(patch){const task=chain.then(async()=>{data=await api.save(patch);success();return true;});chain=task.catch(()=>{});return task;}
function position(){const active=tabs.find(t=>t.getAttribute('aria-selected')==='true');indicator.style.height=active.offsetHeight+'px';indicator.style.transform=`translateY(${active.offsetTop}px)`;}
async function select(tab,save=true){if(save&&ready&&!await saveCurrent(true))return;if(tab.dataset.panel!=='operation')await stopMicrophoneTest();for(const t of tabs){const active=t===tab;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;$(t.dataset.panel).hidden=!active;}position();if(tab.dataset.panel==='history')renderHistory();}
new ResizeObserver(position).observe(document.querySelector('nav'));
tabs.forEach((tab,i)=>{tab.onclick=()=>select(tab).catch(report);tab.onkeydown=e=>{let n;if(e.key==='ArrowDown')n=(i+1)%tabs.length;if(e.key==='ArrowUp')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();select(tabs[n]).then(()=>tabs[n].focus()).catch(report);}};});
function color(value){document.documentElement.style.setProperty('--accent',value);document.documentElement.style.setProperty('--on-accent',value==='#262626'?'#fff':'#222');document.querySelectorAll('.dot').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.color===value)));}
for(const [name,value] of [['白黒','#262626'],['黄色','#EBD48A'],['青','#9BACDC'],['赤','#DC9B97'],['ピンク','#E7B2CC'],['オレンジ','#E8BA91'],['緑','#9FC3AD'],['水色','#9ECEDE'],['黄緑','#C4D59B']]){const b=document.createElement('button');b.className='dot';b.dataset.color=value;b.style.background=value;b.title=name;b.setAttribute('aria-label',name);b.onclick=async()=>{try{await persist({accent:value});color(value);}catch(e){report(e)}};document.querySelector('.dots').append(b);}
function fill(){const s=data.settings;$('continuation-assist').checked=s.continuationAssist;$('fast-start').checked=s.fastStart;qualityFill(s);extraFill();microphoneFill(s);color(s.accent);$('shortcut').dataset.key=s.shortcut;$('shortcut').value=shortcutLabel(s.shortcut);document.querySelector(`[name=mode][value=${s.liveInput?'live':'after'}]`).checked=true;$('show-taskbar').checked=s.showTaskbar;$('launch-startup').checked=s.launchAtStartup;$('limit-count').value=s.count;$('limit-chars').value=s.chars;$('ime-auto-import').checked=s.imeAutoImport;$('term-list').replaceChildren();s.terms.forEach(term);$('version').textContent=data.version;$('data-path').textContent=data.dataPath;renderHistory();busy(data.phase);}
function busy(phase){data.phase=phase;if(phase!=='idle')stopMicrophoneTest().catch(report);$('phase-note').hidden=phase==='idle';document.body.classList.toggle('busy',phase!=='idle');for(const control of document.querySelectorAll('section input,section select,section button:not(.copy)'))control.disabled=phase!=='idle';renderCommandModel();updateMcpInstall();}
for(const id of ['shortcut','command-shortcut']){
 const field=$(id);let single=null;
 const assign=key=>{field.dataset.key=key;field.value=shortcutLabel(key);};
 field.onkeydown=e=>{
  e.preventDefault();if(e.repeat)return;
  if(['Control','Alt','Shift','Meta'].includes(e.key)){single=!e.shiftKey&&!e.metaKey&&Number(e.ctrlKey)+Number(e.altKey)===1&&/^(Control|Alt)(Left|Right)$/.test(e.code)?e.code:null;return;}
  single=null;
  const punctuation={Comma:',',Period:'.',Slash:'/',Semicolon:';',Quote:"'",BracketLeft:'[',BracketRight:']',Minus:'-',Equal:'='};
  const key=punctuation[e.code]||(e.code==='Space'?'Space':/^Key[A-Z]$/.test(e.code)?e.code.slice(3):/^Digit[0-9]$/.test(e.code)?e.code.slice(5):/^(F\d{1,2}|Home|End|Insert|Delete|PageUp|PageDown)$/.test(e.key)?e.key:/^Arrow(Up|Down|Left|Right)$/.test(e.key)?e.key.slice(5):null);
  if(!key||!e.ctrlKey&&!e.altKey&&!e.metaKey){report(new Error('Ctrl・Alt・Winを含む組み合わせ、または左右Ctrl・Alt単独を指定してください。'));return;}
  assign([e.ctrlKey&&'CommandOrControl',e.altKey&&'Alt',e.shiftKey&&'Shift',e.metaKey&&'Super',key].filter(Boolean).join('+'));
 };
 field.onkeyup=e=>{e.preventDefault();if(single===e.code){if(id==='shortcut')assign(single);else report(new Error('押して話すコマンドは別のキーと組み合わせてください。'));}single=null;};
 field.addEventListener('blur',()=>{single=null});
}

async function saveOperation(){if(!ready)return true;const commandShortcut=$('command-shortcut').dataset.key,shortcut=$('shortcut').dataset.key,liveInput=document.querySelector('[name=mode]:checked').value==='live';if(commandShortcut===data.settings.commandShortcut&&shortcut===data.settings.shortcut&&liveInput===data.settings.liveInput)return true;await persist({shortcut,commandShortcut,liveInput});return true;}
$('fast-start').onchange=()=>persist({fastStart:$('fast-start').checked}).catch(report);
$('continuation-assist').onchange=()=>persist({continuationAssist:$('continuation-assist').checked}).catch(report);
$('command-shortcut').onblur=()=>saveOperation().catch(report);$('shortcut').onblur=()=>saveOperation().catch(report);document.querySelectorAll('[name=mode]').forEach(i=>i.onchange=()=>saveOperation().catch(report));
function term(value={term:'',reading:''}){const row=document.createElement('tr');row.className='term';for(const [name,label] of [['term','正しい表記'],['reading','読み']]){const cell=document.createElement('td'),input=document.createElement('input');input.dataset.key=name;input.setAttribute('aria-label',label);input.maxLength=name==='term'?80:120;input.value=value[name];input.onblur=()=>saveTerms(false).catch(report);cell.append(input);row.append(cell);}const cell=document.createElement('td'),remove=document.createElement('button');remove.className='delete-term';remove.textContent='×';remove.setAttribute('aria-label','この用語を削除');remove.onclick=async()=>{try{await saveTerms(false,row);row.remove();}catch(e){report(e)}};cell.append(remove);row.append(cell);$('term-list').append(row);}
async function saveTerms(clean=false,excluded=null){await saveReplacements(clean);const rows=[...document.querySelectorAll('.term')];const terms=rows.filter(r=>r!==excluded).map(r=>Object.fromEntries([...r.querySelectorAll('input')].map(i=>[i.dataset.key,i.value.trim()]))).filter(t=>t.term||t.reading);if(JSON.stringify(terms)!==JSON.stringify(data.settings.terms))await persist({terms});if(clean)for(const row of rows)if(![...row.querySelectorAll('input')].some(i=>i.value.trim()))row.remove();return true;}
$('add-term').onclick=()=>{if($('term-list').children.length>=100){report(new Error('用語は100件までです。'));return;}term();$('term-list').lastElementChild.querySelector('input').focus();};
async function saveDetails(){const count=Number($('limit-count').value),chars=Number($('limit-chars').value),showTaskbar=$('show-taskbar').checked,launchAtStartup=$('launch-startup').checked;if(!$('limit-count').value||!$('limit-chars').value||!Number.isInteger(count)||count<0||count>1000||!Number.isInteger(chars)||chars<1||chars>12000)throw new Error('保存件数は0〜1000件、最大文字数は1〜12000文字です。');const patch={count,chars,showTaskbar,launchAtStartup,saveAudio:$('save-audio').checked};if(Object.entries(patch).some(([k,v])=>v!==data.settings[k]))await persist(patch);return true;}
for(const id of ['limit-count','limit-chars'])$(id).onblur=()=>saveDetails().catch(report);for(const id of ['show-taskbar','launch-startup','save-audio'])$(id).onchange=()=>saveDetails().catch(report);
async function saveCurrent(clean=false){try{if(!ready)return true;const active=tabs.find(t=>t.getAttribute('aria-selected')==='true').dataset.panel;return active==='terms'?await saveTerms(clean):active==='operation'?await saveOperation():active==='details'?await saveDetails():true;}catch(e){report(e);return false;}}
async function close(){if(await saveCurrent(true)){await chain;await stopMicrophoneTest();await api.closeSettings();}}
$('close-settings').onclick=()=>close().catch(report);api.on('request-close',()=>close().catch(report));
function renderHistory(){if(!data)return;const signature=JSON.stringify([data.history,data.latest,data.settings.count]);if(signature===historySignature)return;historySignature=signature;const scroll=$('history').scrollTop;const drafts=new Map([...$('entries').children].filter(e=>e.dataset.id).map(e=>[e.dataset.id,e.querySelector('textarea').value]));const entries=[...data.history];if(data.latest&&!entries.some(e=>e.id===data.latest.id))entries.unshift({...data.latest,temporary:true});$('count').textContent=`${data.history.length} / ${data.settings.count} 件`;$('entries').replaceChildren();for(const entry of entries){const row=document.createElement('article');row.className='entry';row.dataset.id=entry.id;const meta=document.createElement('div');meta.className='meta';const date=document.createElement('span');date.textContent=new Date(entry.at).toLocaleString('ja-JP')+' · '+entry.status+(entry.temporary?' · 未保存':'');const actions=document.createElement('div');actions.className='entry-actions';const content=document.createElement('textarea');content.value=drafts.get(entry.id)??entry.text;content.setAttribute('aria-label','文字起こし結果');const copy=document.createElement('button');copy.className='copy';copy.title='全文をコピー';copy.setAttribute('aria-label','全文をコピー');copy.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/></svg>';copy.onclick=async()=>{try{await api.copy(content.value);$('status').classList.remove('error');$('status').textContent='コピーしました。';}catch(e){report(e)}};const paste=document.createElement('button');paste.className='paste-button';paste.textContent='クリックして貼り付け';paste.onclick=async()=>{try{await api.pasteAtCursor(content.value);$('status').textContent='貼り付けました。';}catch(e){report(e)}};const remove=document.createElement('button');remove.className='delete-history';remove.textContent='×';remove.title='この履歴を削除';remove.setAttribute('aria-label','この履歴を削除');remove.onclick=()=>{pendingAction={id:entry.id};$('confirm-title').textContent='この履歴を削除してよろしいですか？';$('confirm-description').textContent='この履歴1件を削除します。保存した音声は「録音から再認識」から削除できます。';$('confirm-dialog').showModal();$('confirm-cancel').focus();};actions.append(copy,paste,remove);meta.append(date,actions);row.append(meta,content);if(entry.original){const raw=document.createElement('details'),summary=document.createElement('summary'),p=document.createElement('p');summary.textContent=entry.original===entry.text?'認識原文（補正なし）':'認識原文と比較';p.className='raw';p.textContent=entry.original;raw.append(summary,p);row.append(raw);}$('entries').append(row);}if(!entries.length)$('entries').textContent='履歴はありません。';$('history').scrollTop=scroll;busy(data.phase);}
const confirmations={reset:['設定をデフォルトに戻してよろしいですか？','履歴と辞書は残ります。'],all:['履歴と辞書をすべて削除してよろしいですか？','通常の履歴・マイク音声・用語・表記置換を削除します。会議の結果は個別に削除してください。'],history:['履歴をすべて削除してよろしいですか？','通常の履歴と保存したマイク音声を削除します。会議ファイルの結果・辞書・設定は残ります。'],terms:['辞書をすべて削除してよろしいですか？','履歴と設定は残ります。削除は元に戻せません。']};
document.querySelectorAll('[data-danger]').forEach(button=>button.onclick=async()=>{if(!await saveCurrent(true))return;pendingAction=button.dataset.danger;$('confirm-title').textContent=confirmations[pendingAction][0];$('confirm-description').textContent=confirmations[pendingAction][1];$('confirm-dialog').showModal();$('confirm-cancel').focus();});$('confirm-cancel').onclick=()=>$('confirm-dialog').close();$('confirm-dialog').addEventListener('close',()=>pendingAction=null);
$('confirm-yes').onclick=async()=>{if(!pendingAction)return;$('confirm-yes').disabled=true;try{await chain;if(pendingAction.recordingId){await api.recordingDelete(pendingAction.recordingId);await renderRecordings();}else if(pendingAction.meetingId){await api.meetingDelete(pendingAction.meetingId);meeting=null;$('meeting-detail').hidden=true;await meetingList();}else{data=typeof pendingAction==='object'?await api.deleteHistory(pendingAction.id):await api.destroy(pendingAction);fill();await renderRecordings();}$('confirm-dialog').close();$('status').textContent='完了しました。';}catch(e){$('confirm-description').textContent=e.message;}finally{$('confirm-yes').disabled=false;}};
api.on('data-changed',value=>{data=value;renderHistory();color(value.settings.accent);renderCommandModel();extraFill();});api.on('phase-changed',value=>{if(data)busy(value)});api.on('notice',message=>report(new Error(message)));api.on('select-tab',name=>select(tabs.find(t=>t.dataset.panel===name)||tabs[0],false).catch(report));
window.addEventListener('DOMContentLoaded',()=>api.snapshot().then(value=>{data=value;fill();ready=true;position();if(value.notice)report(new Error(value.notice));}).catch(report));

async function importTerms(fromFile=false){
 if(!await saveCurrent(true))return;
 for(const c of $('terms').querySelectorAll('input,button'))c.disabled=true;
 $('status').textContent=fromFile?'辞書ファイルを選択…':'Windows辞書を取り込み中…';$('status').classList.remove('error');
 try{const result=await(fromFile?api.importDictionaryFile():api.importIme());if(result.canceled){$('status').textContent='';return;}data=result;$('term-list').replaceChildren();data.settings.terms.forEach(term);$('ime-auto-import').checked=data.settings.imeAutoImport;const s=data.importStats;$('status').textContent=`${fromFile?'辞書ファイル':'Windows辞書'}: ${s.added}件追加、${s.duplicates}件重複`+(s.skipped?`、対象外${s.skipped}件`:'')+(s.overflow?`。上限100件のため${s.overflow}件は未取り込みです。`:'。');}
 catch(e){report(e);}finally{busy(data.phase);}
}
$('import-ime').onclick=()=>importTerms().catch(report);
$('import-file').onclick=()=>importTerms(true).catch(report);
$('ime-auto-import').onchange=async()=>{try{await persist({imeAutoImport:$('ime-auto-import').checked});if(data.settings.imeAutoImport)await importTerms();}catch(e){$('ime-auto-import').checked=data.settings.imeAutoImport;report(e);}};

$('export-ime').onclick=async()=>{if(!await saveCurrent(true))return;try{const result=await api.exportIme();if(!result.canceled){$('status').classList.remove('error');$('status').textContent=`辞書を${result.count}件書き出しました。`;}}catch(e){report(e)}};
